### ISSUE TITLE
Disable css aggregation on font-face.css 

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#136]
We recently identified a problem on Croydon with custom fonts not working once the site is deployed. This was fixed by disabling css aggregation on font-face.css - this change should be replicated back to the base theme ... more info here: https://github.com/localgovdrupal/localgov_theme_croydon/pull/17

**Comment by cjstevens78** [comment]
PR for this here: https://github.com/localgovdrupal/localgov_theme/pull/139

**Comment by andybroomfield** [comment]
Whats the issue with the CSS agregation? Could be better to make sure its included first and a dependency for the theme styles rather that removing aggregation altogether?

**Comment by cjstevens78** [comment]
@Adnan-cds can you take a look at Andy's comment above plz thanks

**Comment by Adnan-cds** [comment]
Hi Andy,
When we use a font file **bundled** with the theme, the built-in CSS aggregation breaks the font path (e.g /foo/bar/baz-font.woff2).  This doesn't happen when fonts are fetched from a URL (e.g. https://example.net/baz-font.woff2).  This is a [known issue](https://drupal.stackexchange.com/questions/123520/font-your-face-dont-work-when-aggregate-and-compress-css-files-is-enabled).

**Comment by andybroomfield** [comment]
I've just done some testings, and it looks like the issue is actully limited to only the svg font, removing that makes it work with aggregation.
````css
@font-face {
  font-family: 'Roboto Regular';
  font-weight: normal;
  font-style: normal;
  src: url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.eot'),
       url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.eot?#iefix') format('embedded-opentype'),
       url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.woff2') format('woff2'),
       url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.woff') format('woff'),
       url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.ttf') format('truetype');
}

@font-face {
  font-family: 'Maven Pro Bold';
  font-weight: bold;
  font-style: normal;
  src: url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.eot'),
       url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.eot?#iefix') format('embedded-opentype'),
       url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.woff2') format('woff2'),
       url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.woff') format('woff'),
       url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.ttf') format('truetype');
}
````

The SVG fonts themselves have references to `Open Sans` which might not be the correct font.
````css
url('../fonts/roboto-regular/4fb585f7f5a2d493cd85baeba22cc983.svg#Open Sans Regular') format('svg'); // iOS 4.1-
````
and 
````css
url('../fonts/maven-pro-bold/9280a336215bd036e843a066d1dc1bd2.svg#Open Sans Bold') format('svg'); // iOS 4.1-
````
These are for targeting really old versions of iOS. I Think most will have updated by now and thats safe to remove?
