### ISSUE TITLE
Add documentation for how to create child theme

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#76]
Write up steps to build a child theme.
Based on what was needed to create [Localgov Theme BHCC](https://github.com/localgovdrupal/localgov_theme_bhcc).

----
1. Generate child theme, declaring parent theme with `base theme: localgov_theme` in `...info.yml`
2. Generate a libraries file `THEMENAME.libraries.yml` with the `global` css library theme key as `assets/css/lib/main.css: {}`
3. Copy the `assets` folder, `package.json` `package.lock` and `gulpfile.js` in localgov_theme into child theme.
4. cd into the child theme directory and run `nom install`
5. copy `assets/scss/lib/_variables.scss` into `assets/scss/lib/_variables-THEMENAME.scss`
6. in `assets/scss/lib/main.scss` add line `@import 'variables-THEMENAME';` and optionally comment out line `@import 'variables';` (or include your custom variables below it).
7. Customise the required fonts and colours (todo: Document the required variables)
8. If custom styles are required, add them to `theme.scss` and move the import `@import 'theme';` to the bottom (todo: Make this change in localgov_theme).
9. cd into assets directory and run `sass scss:css` (use the `--watch` option when developing).
10. Add the following to theme.info file to disable `localgov_theme` styles :
````
# Switch off Localgov theme styles.
libraries-override:
  localgov_theme/global:
    css:
      theme:
        assets/css/font-face.css: false
        assets/css/lib/main.css: false
````
11. In the Drupal site, under appearance, select install and set default for newly created theme.
